#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Enable python package installation
INSTALL_PYTHON_PACKAGES="true"

# Run the shared bootstrap script
source ./script/include/run_bootstrap
