#!/bin/bash

# script/demo_client: run the demo client
source "$(dirname "${0}")"/../script/demo_secret
source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Launch the client
run_command "python ./demo/flask_client.py"
